### PR TITLE
Added BlackBerry 10 support

### PR DESCRIPTION
**Pull request by FelipeGualberto**
Functions added to BlackBerry 10: Keyboard.show , Keyboard.close

Events added to BlackBerry 10: native.keyboardshow, native.keyboardhide

### CODE REVIEW

**Comment by tlancina** [comment]
Hey thanks for this! One small nitpick - would you mind cleaning up the formatting changes that snuck into keyboard.js?

**Comment by tlancina** [comment]
Hah looks like the formatting was weird already to begin with! I'll just do it myself.  Thanks again!

**Comment by FelipeGualberto** [comment]
You´re welcome :) Any problem with BlackBerry 10 just tell me!
Would you please update in the Cordova site? http://plugins.cordova.io/#/package/com.ionic.keyboard

**Comment by tlancina** [comment]
Hey sorry - took me a bit to track down our user account for plugman, should be updated now!

**Pull request merged**
